apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkodes-shipSafe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipSafe
  template:
    metadata:
      labels:
        app: shipSafe
    spec:
      containers:
        - name: kkodes-shipSafe
          image: 904941000330.dkr.ecr.us-east-2.amazonaws.com/kkodes-apps:shipSafe-v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: shipSafe-svc
spec:
  selector:
    app: shipSafe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
